name: RDP

on:
  workflow_dispatch:

jobs:
  secure-rdp:
    runs-on: ubuntu-24.04
    timeout-minutes: 3600

    steps:
      - name: Configure Core RDP Settings
        run: |
          sudo apt-get update
          sudo apt-get install xfce4 xfce4-goodies -y
          sudo apt-get install xrdp -y

      - name: Xsession setup for auto-init of GUI and service xrdp
        run: |
          sudo systemctl enable xrdp
          sudo systemctl start xrdp
          $ echo "xfce4-session" | tee .xsession
          sudo sudo ss -pnl | grep 3389

      - name: Configurar firewall para permitir RDP na porta 3389
        run: |
          sudo ufw allow 3389/tcp
          sudo ufw reload

      - name: Criar usuário RDP com senha segura
        id: create_user
        run: |
          PASSWORD=$(tr -dc 'A-Za-z0-9!@#$%^&*()_+-=' </dev/urandom | head -c 16)
          sudo useradd -m -s /bin/bash RDP
          echo "RDP:$PASSWORD" | sudo chpasswd
          sudo usermod -aG sudo RDP

          echo "RDP_CREDS=User: RDP | Password: $PASSWORD" >> $GITHUB_ENV

          # Verificar se o usuário foi criado
          if ! id -u RDP > /dev/null 2>&1; then
            echo "User creation failed"
            exit 1
          fi

      - name: Instalar Tailscale
        run: |
         curl -fsSL https://tailscale.com/install.sh | sh
         sudo tailscale up

      - name: Estabelecer conexão Tailscale
        env:
          TAILSCALE_AUTH_KEY: ${{ secrets.TAILSCALE_AUTH_KEY }}
          GITHUB_RUN_ID: ${{ github.run_id }}
        run: |
          sudo tailscale up --authkey=$TAILSCALE_AUTH_KEY --hostname=gh-runner-$GITHUB_RUN_ID

          TS_IP=""
          RETRIES=0
          until [ -n "$TS_IP" ] || [ $RETRIES -ge 10 ]; do
            TS_IP=$(tailscale ip -4)
            sleep 5
            RETRIES=$((RETRIES+1))
          done

          if [ -z "$TS_IP" ]; then
            echo "Tailscale IP not assigned. Exiting."
            exit 1
          fi

          echo "TAILSCALE_IP=$TS_IP" >> $GITHUB_ENV

      - name: Verificar acessibilidade do RDP
        run: |
          echo "Tailscale IP: $TAILSCALE_IP"
          nc -zv $TAILSCALE_IP 3389
          if [ $? -ne 0 ]; then
            echo "TCP connection to RDP port 3389 failed"
            exit 1
          fi
          echo "TCP connectivity successful!"

      - name: Manter conexão ativa
        run: |
          echo -e "\n=== RDP ACCESS ==="
          echo "Address: $TAILSCALE_IP"
          echo "Username: RDP"
          echo "Password: $RDP_CREDS"
          echo "==================\n"

          while true; do
            echo "[$(date)] RDP Active - Use cancel to stop"
            sleep 300
          done
